<?php

/* /home/salinabyabc/public_html/themes/jtherczeg-corlate/pages/samples/politica-confidentialitate.htm */
class __TwigTemplate_ff9248b59fccbb8042a25a1371e28a6f648f9cc28a18d02f4e2ff247a6f41fb3 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "<section id=\"feature\" class=\"transparent-bg\" style=\"padding-top: 100px\">
        <div class=\"container\">
           <div class=\"center wow fadeInDown\">
                <h2 style=\"text-align: center;\">Politica de confidentialitate</h2>
<p class=\"wall-of-text\" style=\"text-align: justify;\">ACVATIC BEBE CLUB SRL, prin intermediul site-ului www.salinabyabc.ro isi ia angajamentul de a va proteja datele personale. Puteti vizita cea mai mare parte a site-ului www.acvaticbebeclub.ro fara a ne oferi datele dvs. personale, cum ar fi numele, adresa sau email-ul. Cu toate acestea, anumite informatii sunt obtinute prin mijloace automate, atunci cand vizitati site-ul, utilizand cookie-uri si tag-uri pixel, care reprezinta instrumente standard in industria internetului. Utilizarea cookie-urilor si tag-urilor pixel ne permite sa va aflam IP-ul, tipul de browser pe care il folositi si activitatea generala a browser-ului.</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Cu toate acestea, niciuna dintre informatiile furnizate de dvs. nu va fi cunoscuta de o parte terta decat pentru marketing si au fost luate toate masurile necesare ca toate informatiile personale sa ramana confidentiale.&nbsp;Aveti posibilitatea de a va revizui, modifica sau de a cere stergerea datelor sau de a va dezabona de la newsletter printr-un click pe butonul &bdquo;dezabonare&rdquo;.</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\">Ce este un &bdquo;cookie&rdquo;?</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Un &bdquo;Internet Cookie&rdquo; (termen cunoscut si ca &bdquo;browser cookie&rdquo; sau &bdquo;HTTP cookie&rdquo; sau pur si simplu &bdquo;cookie&rdquo; ) este un fisier de mici dimensiuni, format din litere si numere, care va fi stocat pe computerul, terminalul mobil sau alte echipamente ale unui utilizator de pe care se acceseaza Internetul.</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Cookie-ul este instalat prin solicitara emisa de catre un web-server unui browser (ex: Internet Explorer, Firefox, Chrome) si este complet &bdquo;pasiv&rdquo; (nu contine programe software, virusi sau spyware si nu poate accesa informatiile de pe hard driveul utilizatorului).</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Un cookie este format din 2 parti: numele si continutul sau valoarea cookie-ului. Mai mult, durata de existenta a unui cookie este determinata; tehnic, doar webserverul care a trimis cookie-ul il poate accesa din nou in momentul in care un utilizator se intoarce pe website-ul asociat webserverului respectiv.</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Cookie-urile in sine nu solicita informatii cu caracter personal pentru a putea fi utilizate si, in cele mai multe cazuri, nu identifica personal utilizatorii de internet.</p>
<p class=\"wall-of-text\" style=\"text-align: justify;\"><br /> Exista 2 categorii mari de cookie-uri:</p>
<ul style=\"text-align: justify;\">
<li class=\"wall-of-text\">Cookieuri de sesiune &ndash; acestea sunt stocate temporar in dosarul de cookie-uri al browserului web pentru ca acesta sa le memoreze pana cand utilizatorul iese de pe web-siteul respectiv sau inchide fereastra browserului (ex: in momentul logarii/delogarii pe un cont de webmail sau pe retele de socializare).</li>
<li class=\"wall-of-text\">Cookieuri Persistente &ndash; acestea sunt stocate pe hard-drive-ul unui computer sau echipament (si in general depinde de durata de viata prestabilita pentru cookie). Cookie-urile persistente le includ si pe cele plasate de un alt website decat cel pe care il viziteaza utilizatorul la momentul respectiv &ndash; cunoscute sub numele de &lsquo;third party cookies&rsquo; (cookieuri plasate de terti) &ndash; care pot fi folosite in mod anonim pentru a memora interesele unui utilizator, astfel incat sa fie livrata publicitate cat mai relevanta pentru utilizatori.</li>
</ul>
<p style=\"text-align: justify;\">Care sunt avantajele cookie-urilor?</p>
<p style=\"text-align: justify;\"><br /> Un cookie contine informatii care fac legatura intre un web-browser (utilizatorul) si un web-server anume (website-ul). Daca un browser acceseaza acel web-server din nou, acesta poate citi informatia deja stocata si reactiona in consecinta.<br /> Cookie-urile asigura userilor o experienta placuta de navigare si sustin eforturile multor websiteuri pentru a oferi servicii confortabile utilizatorillor: ex &ndash; preferintele in materie de confidentialitate online, optiunile privind limba site-ului sau publicitate relevanta.</p>
<p style=\"text-align: justify;\"><br /> Care este durata de viata a unui cookie?</p>
<p style=\"text-align: justify;\"><br /> Cookie-urile sunt administrate de webservere. Durata de viata a unui cookie poate varia semnificativ, depinzand de scopul pentru care este plasat. Unele cookie-uri sunt folosite exclusive pentru o singura sesiune (session cookies) si nu mai sunt retinute odata de utilizatorul a parasite website-ul si unele cookie-uri sunt retinute si refolosite de fiecare data cand utilizatorul revine pe acel website (&lsquo;cookie-uri permanente&rsquo;). Cu toate aceste, cookie-urile pot fi sterse de un utilizator in orice moment prin intermediul setarilor browserului.</p>
<p style=\"text-align: justify;\">Ce sunt cookie-urile plasate de terti?</p>
<p style=\"text-align: justify;\"><br /> Anumite sectiuni de continut de pe unele site-uri pot fi furnizate prin intermediul unor terte parti/furnizori (ex: news box, un video sau o reclama). Aceste terte parti pot plasa de asemenea cookieuri prin intermediul site-ului si ele se numesc &bdquo;third party cookies&rdquo; pentru ca nu sunt plasate de proprietarul website-ului respectiv. Furnizorii terti trebuie sa respecte de asemenea legea in vigoare si politicile de confidentialitate ale detinatorului site-ului.</p>
<p style=\"text-align: justify;\">Ce tip de informatii sunt stocate si accesate prin intermediul cookie-urilor?</p>
<p style=\"text-align: justify;\"><br /> Cookie-urile pastreaza informatii intr-un fisier text de mici dimensiuni care permit unui website sa recunoasca un browser. Webserverul va recunoaste browserul pana cand cookie-ul expira sau este sters. Cookie-ul stocheaza informatii importante care imbunatatesc experienta de navigare pe Internet (ex: setarile limbii in care se doreste accesarea unui site; pastrarea unui user logat in contul de webmail; securitatea online banking; pastrarea produselor in cosul de cumparaturi, etc).</p>
<p style=\"text-align: justify;\">De ce sunt cookie-urile importante pentru Internet?</p>
<p style=\"text-align: justify;\"><br /> Cookie-urile reprezinta punctul central al functionarii eficiente a Internetului, ajutand la generarea unei experiente de navigare prietenoase si adaptata preferintelor si intereselor fiecarui utilizator. Refuzarea sau dezactivarea cookieurilor poate face unele site-uri imposibil de folosit.</p>
<p style=\"text-align: justify;\">Refuzarea sau dezactivarea cookie-urilor nu inseamna ca nu veti mai primi publicitate online &ndash; ci doar ca aceasta nu va mai putea tine cont de preferintele si interesele dvs, evidentiate prin comportamentul de navigare.</p>
<p style=\"text-align: justify;\">Exemple de intrebuintari importante ale cookieurilor (care nu necesita autentificarea unui utilizator prin intermediul unui cont):<br /> &ndash; Continut si servicii adaptate preferintelor utilizatorului &ndash; categorii de stiri, vreme, sport, harti, servicii publice si guvernamentale, site-uri de entertainment si servicii de travel.<br /> &ndash; Oferte adaptate pe interesele utilizatorilor &ndash; retinerea parolelor, preferintele de limba (ex: afisarea rezultatelor cautarilor in limba Romana).<br /> &ndash; Retinerea filtrelor de protectie a copiilor privind continutul pe Internet (optiuni family mode, functii de safe search).<br /> &ndash; Limitarea frecventei de difuzare a reclamelor &ndash; limitarea numarului de afisari a unei reclame pentru un anumit utilizator pe un site.<br /> &ndash; Furnizarea de publicitate mai relevanta pentru utilizator.<br /> &ndash; Masurarea, optimizare si caracteristicile de analytics &ndash; cum ar fi confirmarea unui anumit nivel de trafic pe un website, ce tip de continut este vizualizat si modul cum un utilizator ajunge pe un website (ex. prin motoare de cautare, direct, din alte website-uri etc). Website-urile deruleaza aceste analize a utilizarii lor pentru a imbunatati site-urile in beneficiul userilor.<br /> &ndash; Securitate si probleme legate de confidentialitate</p>
<p style=\"text-align: justify;\">Cookieurile NU sunt virusi ! Ele folosesc formate tip plain text. Nu sunt alcatuite din bucati de cod asa ca nu pot fi executate nici nu pot auto-rula. In consecinta, nu se pot duplica sau replica pe alte retele pentru a se rula sau replica din nou. Deoarece nu pot indeplini aceste functii, nu pot fi considerate virusi.</p>
<p style=\"text-align: justify;\"><br /> Cookie-urile pot fi totusi folosite pentru scopuri negative. Deoarece stocheaza informatii despre preferintele si istoricul de navigare al utilizatorilor, atat pe un anume site cat si pe mai multe alte siteuri, cookieurile pot fi folosite ca o forma de Spyware. Multe produse anti-spyware sunt constiente de acest fapt si in mod constant marcheaza cookie-urile pentru a fi sterse in cadrul procedurilor de stergere/scanare anti-virus/anti-spyware.</p>
<p style=\"text-align: justify;\"><br /> In general browserele au integrate setari de confidentialitate care furnizeaza diferite nivele de acceptare a cookieurilor, perioada de valabilitate si stergere automata dupa ce utilizatorul a vizitat un anumit site.</p>
<p style=\"text-align: justify;\">Alte aspecte de securitate legate de cookie-uri</p>
<p style=\"text-align: justify;\"><br /> Deoarece protectia identitatii este foarte valoroasa si reprezinta dreptul fiecarui utilizator de internet, este indicat sa se stie ce eventuale probleme pot crea cookie-urile. Pentru ca prin intermediul lor se transmit in mod constant in ambele sensuri informatii intre browser si website, daca un atacator sau persoana neautorizata intervine in parcursul de transmitere a datelor, informatiile continute de cookie pot fi interceptate. Desi foarte rar, acest lucru se poate intampla daca browserul se conecteaza la server folosind o retea necriptata (ex: o retea WiFi nesecurizata).</p>
<p style=\"text-align: justify;\"><br /> Alte atacuri bazate pe cookie implica setari gresite ale cookieurilor pe servere. Daca un website nu solicita browserului sa foloseasca doar canale criptate, atacatorii pot folosi aceasta vulnerabilitate pentru a pacali browserele in a trimite informatii prin intermediul canalelor nesecurizate. Atacatorii utilizeaza apoi informatiile in scopuri de a accesa neautorizat anumite site-uri. Este foarte important sa fiti atenti in alegerea metodei celei mai potrivite de protectie a informatiilor personale.<br /> Sfaturi pentru o navigare sigura si responsabila, bazata pe cookies.</p>
<p style=\"text-align: justify;\"><br /> Datorita flexibilitatii lor si a faptului ca majoritatea dintre cele mai vizitate site-uri si cele mai mari folosesc cookieuri, acestea sunt aproape inevitabile. Dezactivarea cookie-urilor nu va permite accesul utilizatorului pe site-urile cele mai raspandite si utilizate printre care Youtube, Gmail, Yahoo si altele.</p>
<p style=\"text-align: justify;\"><br /> Iata cateva sfaturi care va pot asigura ca navigati fara griji insa cu ajutorul cookieurilor:<br /> &ndash; Particularizati-va setarile browserului in ceea ce priveste cookie-urile pentru a reflecta un nivel confortabil pentru voi al securitatii utilizarii cookie-urilor.<br /> &ndash; Daca nu va deranjeaza cookie-urile si sunteti singura persoana care utilizaeaza computerul, puteti seta termene lunigi de expirare pentru stocarea istoricului de navigare si al datelor personale de acces.<br /> &ndash; Daca impartiti accesul la calculator, puteti lua in considerare setarea browserului pentru a sterge datele individuale de navigare de fiecare data cand inchideti browserul. Aceasta este o variant de a accesa site-urile care plaseaza cookieuri si de a sterge orice informatie de vizitare la inchiderea sesiunii navigare.<br /> &ndash; Instalati-va si updatati-va constant aplicatii antispyware.</p>
<p style=\"text-align: justify;\">Multe dintre aplicatiile de detectare si prevenire a spyware-ului includ detectarea atacurilor pe site-uri.<br /> Astfel, impiedica browserul de la a accesa website-uri care ar putea sa exploateze vulnerabilitatile browserului sau sa descarce software periculos. Asigurati-va ca aveti browserul mereu updatat. Multe dintre atacurile bazate pe cookies se realizeaza exploatand punctele slabe ale versiunilor vechi ale browserelor.</p>
<p style=\"text-align: justify;\"><br /> Cookie-urile sunt pretutindeni si nu pot fi evitate daca doriti sa va bucurati de acces pe cele mai bune si cele mai mari site-uri de pe Internet &ndash; locale sau internationale. Cu o intelegere clara a modului lor de operare si a beneficiilor pe care le aduc, puteti lua masurile necesare de securitate astel incat sa puteti naviga cu incredere pe internet.</p>
<p style=\"text-align: justify;\">Cum pot opri cookie-urile?</p>
<p style=\"text-align: justify;\"><br /> Dezactivarea si refuzul de a primi cookie-uri pot face anumite site-uri impracticabile sau dificil de vizitat si folosit. De asemenea, refuzul de a accepta cookie-uri nu inseamna ca nu veti mai primi/vedea publicitate online.</p>
<p style=\"text-align: justify;\"><br /> Este posibila setarea din browser pentru ca aceste cookie-uri sa nu mai fie acceptate sau poti seta browserul sa accepte cookie-uri de la un site anume. Dar, de exemplu, daca nu esti inregistat folosind cookie-urile, nu vei putea lasa comentarii.<br /> Toate browserele moderne ofera posibilitatea de a schimba setarile cookie-urilor. Aceste setari se gasesc de regula in &bdquo;optiuni&rdquo; sau in meniul de &bdquo;preferinte&rdquo; al browserului tau.</p>
<p style=\"text-align: justify;\"><br /> Pentru a intelege aceste setari, urmatoarele linkuri pot fi folositoare, altfel puteti folosi optiunea &bdquo;ajutor&rdquo; a browserului pentru mai multe detalii.</p>
<p style=\"text-align: justify;\"><br /> Pentru setarile cookie-urilor generate de terti, puteti consulta si site-ul www.youronlinechoices.com/ro/ unde gasiti mai multe informatii privind confidentialitatea legata de publicitatea online. </p>
            </div>

    </section><!--/#feature-->";
    }

    public function getTemplateName()
    {
        return "/home/salinabyabc/public_html/themes/jtherczeg-corlate/pages/samples/politica-confidentialitate.htm";
    }

    public function getDebugInfo()
    {
        return array (  19 => 1,);
    }
}
/* <section id="feature" class="transparent-bg" style="padding-top: 100px">*/
/*         <div class="container">*/
/*            <div class="center wow fadeInDown">*/
/*                 <h2 style="text-align: center;">Politica de confidentialitate</h2>*/
/* <p class="wall-of-text" style="text-align: justify;">ACVATIC BEBE CLUB SRL, prin intermediul site-ului www.salinabyabc.ro isi ia angajamentul de a va proteja datele personale. Puteti vizita cea mai mare parte a site-ului www.acvaticbebeclub.ro fara a ne oferi datele dvs. personale, cum ar fi numele, adresa sau email-ul. Cu toate acestea, anumite informatii sunt obtinute prin mijloace automate, atunci cand vizitati site-ul, utilizand cookie-uri si tag-uri pixel, care reprezinta instrumente standard in industria internetului. Utilizarea cookie-urilor si tag-urilor pixel ne permite sa va aflam IP-ul, tipul de browser pe care il folositi si activitatea generala a browser-ului.</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Cu toate acestea, niciuna dintre informatiile furnizate de dvs. nu va fi cunoscuta de o parte terta decat pentru marketing si au fost luate toate masurile necesare ca toate informatiile personale sa ramana confidentiale.&nbsp;Aveti posibilitatea de a va revizui, modifica sau de a cere stergerea datelor sau de a va dezabona de la newsletter printr-un click pe butonul &bdquo;dezabonare&rdquo;.</p>*/
/* <p class="wall-of-text" style="text-align: justify;">Ce este un &bdquo;cookie&rdquo;?</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Un &bdquo;Internet Cookie&rdquo; (termen cunoscut si ca &bdquo;browser cookie&rdquo; sau &bdquo;HTTP cookie&rdquo; sau pur si simplu &bdquo;cookie&rdquo; ) este un fisier de mici dimensiuni, format din litere si numere, care va fi stocat pe computerul, terminalul mobil sau alte echipamente ale unui utilizator de pe care se acceseaza Internetul.</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Cookie-ul este instalat prin solicitara emisa de catre un web-server unui browser (ex: Internet Explorer, Firefox, Chrome) si este complet &bdquo;pasiv&rdquo; (nu contine programe software, virusi sau spyware si nu poate accesa informatiile de pe hard driveul utilizatorului).</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Un cookie este format din 2 parti: numele si continutul sau valoarea cookie-ului. Mai mult, durata de existenta a unui cookie este determinata; tehnic, doar webserverul care a trimis cookie-ul il poate accesa din nou in momentul in care un utilizator se intoarce pe website-ul asociat webserverului respectiv.</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Cookie-urile in sine nu solicita informatii cu caracter personal pentru a putea fi utilizate si, in cele mai multe cazuri, nu identifica personal utilizatorii de internet.</p>*/
/* <p class="wall-of-text" style="text-align: justify;"><br /> Exista 2 categorii mari de cookie-uri:</p>*/
/* <ul style="text-align: justify;">*/
/* <li class="wall-of-text">Cookieuri de sesiune &ndash; acestea sunt stocate temporar in dosarul de cookie-uri al browserului web pentru ca acesta sa le memoreze pana cand utilizatorul iese de pe web-siteul respectiv sau inchide fereastra browserului (ex: in momentul logarii/delogarii pe un cont de webmail sau pe retele de socializare).</li>*/
/* <li class="wall-of-text">Cookieuri Persistente &ndash; acestea sunt stocate pe hard-drive-ul unui computer sau echipament (si in general depinde de durata de viata prestabilita pentru cookie). Cookie-urile persistente le includ si pe cele plasate de un alt website decat cel pe care il viziteaza utilizatorul la momentul respectiv &ndash; cunoscute sub numele de &lsquo;third party cookies&rsquo; (cookieuri plasate de terti) &ndash; care pot fi folosite in mod anonim pentru a memora interesele unui utilizator, astfel incat sa fie livrata publicitate cat mai relevanta pentru utilizatori.</li>*/
/* </ul>*/
/* <p style="text-align: justify;">Care sunt avantajele cookie-urilor?</p>*/
/* <p style="text-align: justify;"><br /> Un cookie contine informatii care fac legatura intre un web-browser (utilizatorul) si un web-server anume (website-ul). Daca un browser acceseaza acel web-server din nou, acesta poate citi informatia deja stocata si reactiona in consecinta.<br /> Cookie-urile asigura userilor o experienta placuta de navigare si sustin eforturile multor websiteuri pentru a oferi servicii confortabile utilizatorillor: ex &ndash; preferintele in materie de confidentialitate online, optiunile privind limba site-ului sau publicitate relevanta.</p>*/
/* <p style="text-align: justify;"><br /> Care este durata de viata a unui cookie?</p>*/
/* <p style="text-align: justify;"><br /> Cookie-urile sunt administrate de webservere. Durata de viata a unui cookie poate varia semnificativ, depinzand de scopul pentru care este plasat. Unele cookie-uri sunt folosite exclusive pentru o singura sesiune (session cookies) si nu mai sunt retinute odata de utilizatorul a parasite website-ul si unele cookie-uri sunt retinute si refolosite de fiecare data cand utilizatorul revine pe acel website (&lsquo;cookie-uri permanente&rsquo;). Cu toate aceste, cookie-urile pot fi sterse de un utilizator in orice moment prin intermediul setarilor browserului.</p>*/
/* <p style="text-align: justify;">Ce sunt cookie-urile plasate de terti?</p>*/
/* <p style="text-align: justify;"><br /> Anumite sectiuni de continut de pe unele site-uri pot fi furnizate prin intermediul unor terte parti/furnizori (ex: news box, un video sau o reclama). Aceste terte parti pot plasa de asemenea cookieuri prin intermediul site-ului si ele se numesc &bdquo;third party cookies&rdquo; pentru ca nu sunt plasate de proprietarul website-ului respectiv. Furnizorii terti trebuie sa respecte de asemenea legea in vigoare si politicile de confidentialitate ale detinatorului site-ului.</p>*/
/* <p style="text-align: justify;">Ce tip de informatii sunt stocate si accesate prin intermediul cookie-urilor?</p>*/
/* <p style="text-align: justify;"><br /> Cookie-urile pastreaza informatii intr-un fisier text de mici dimensiuni care permit unui website sa recunoasca un browser. Webserverul va recunoaste browserul pana cand cookie-ul expira sau este sters. Cookie-ul stocheaza informatii importante care imbunatatesc experienta de navigare pe Internet (ex: setarile limbii in care se doreste accesarea unui site; pastrarea unui user logat in contul de webmail; securitatea online banking; pastrarea produselor in cosul de cumparaturi, etc).</p>*/
/* <p style="text-align: justify;">De ce sunt cookie-urile importante pentru Internet?</p>*/
/* <p style="text-align: justify;"><br /> Cookie-urile reprezinta punctul central al functionarii eficiente a Internetului, ajutand la generarea unei experiente de navigare prietenoase si adaptata preferintelor si intereselor fiecarui utilizator. Refuzarea sau dezactivarea cookieurilor poate face unele site-uri imposibil de folosit.</p>*/
/* <p style="text-align: justify;">Refuzarea sau dezactivarea cookie-urilor nu inseamna ca nu veti mai primi publicitate online &ndash; ci doar ca aceasta nu va mai putea tine cont de preferintele si interesele dvs, evidentiate prin comportamentul de navigare.</p>*/
/* <p style="text-align: justify;">Exemple de intrebuintari importante ale cookieurilor (care nu necesita autentificarea unui utilizator prin intermediul unui cont):<br /> &ndash; Continut si servicii adaptate preferintelor utilizatorului &ndash; categorii de stiri, vreme, sport, harti, servicii publice si guvernamentale, site-uri de entertainment si servicii de travel.<br /> &ndash; Oferte adaptate pe interesele utilizatorilor &ndash; retinerea parolelor, preferintele de limba (ex: afisarea rezultatelor cautarilor in limba Romana).<br /> &ndash; Retinerea filtrelor de protectie a copiilor privind continutul pe Internet (optiuni family mode, functii de safe search).<br /> &ndash; Limitarea frecventei de difuzare a reclamelor &ndash; limitarea numarului de afisari a unei reclame pentru un anumit utilizator pe un site.<br /> &ndash; Furnizarea de publicitate mai relevanta pentru utilizator.<br /> &ndash; Masurarea, optimizare si caracteristicile de analytics &ndash; cum ar fi confirmarea unui anumit nivel de trafic pe un website, ce tip de continut este vizualizat si modul cum un utilizator ajunge pe un website (ex. prin motoare de cautare, direct, din alte website-uri etc). Website-urile deruleaza aceste analize a utilizarii lor pentru a imbunatati site-urile in beneficiul userilor.<br /> &ndash; Securitate si probleme legate de confidentialitate</p>*/
/* <p style="text-align: justify;">Cookieurile NU sunt virusi ! Ele folosesc formate tip plain text. Nu sunt alcatuite din bucati de cod asa ca nu pot fi executate nici nu pot auto-rula. In consecinta, nu se pot duplica sau replica pe alte retele pentru a se rula sau replica din nou. Deoarece nu pot indeplini aceste functii, nu pot fi considerate virusi.</p>*/
/* <p style="text-align: justify;"><br /> Cookie-urile pot fi totusi folosite pentru scopuri negative. Deoarece stocheaza informatii despre preferintele si istoricul de navigare al utilizatorilor, atat pe un anume site cat si pe mai multe alte siteuri, cookieurile pot fi folosite ca o forma de Spyware. Multe produse anti-spyware sunt constiente de acest fapt si in mod constant marcheaza cookie-urile pentru a fi sterse in cadrul procedurilor de stergere/scanare anti-virus/anti-spyware.</p>*/
/* <p style="text-align: justify;"><br /> In general browserele au integrate setari de confidentialitate care furnizeaza diferite nivele de acceptare a cookieurilor, perioada de valabilitate si stergere automata dupa ce utilizatorul a vizitat un anumit site.</p>*/
/* <p style="text-align: justify;">Alte aspecte de securitate legate de cookie-uri</p>*/
/* <p style="text-align: justify;"><br /> Deoarece protectia identitatii este foarte valoroasa si reprezinta dreptul fiecarui utilizator de internet, este indicat sa se stie ce eventuale probleme pot crea cookie-urile. Pentru ca prin intermediul lor se transmit in mod constant in ambele sensuri informatii intre browser si website, daca un atacator sau persoana neautorizata intervine in parcursul de transmitere a datelor, informatiile continute de cookie pot fi interceptate. Desi foarte rar, acest lucru se poate intampla daca browserul se conecteaza la server folosind o retea necriptata (ex: o retea WiFi nesecurizata).</p>*/
/* <p style="text-align: justify;"><br /> Alte atacuri bazate pe cookie implica setari gresite ale cookieurilor pe servere. Daca un website nu solicita browserului sa foloseasca doar canale criptate, atacatorii pot folosi aceasta vulnerabilitate pentru a pacali browserele in a trimite informatii prin intermediul canalelor nesecurizate. Atacatorii utilizeaza apoi informatiile in scopuri de a accesa neautorizat anumite site-uri. Este foarte important sa fiti atenti in alegerea metodei celei mai potrivite de protectie a informatiilor personale.<br /> Sfaturi pentru o navigare sigura si responsabila, bazata pe cookies.</p>*/
/* <p style="text-align: justify;"><br /> Datorita flexibilitatii lor si a faptului ca majoritatea dintre cele mai vizitate site-uri si cele mai mari folosesc cookieuri, acestea sunt aproape inevitabile. Dezactivarea cookie-urilor nu va permite accesul utilizatorului pe site-urile cele mai raspandite si utilizate printre care Youtube, Gmail, Yahoo si altele.</p>*/
/* <p style="text-align: justify;"><br /> Iata cateva sfaturi care va pot asigura ca navigati fara griji insa cu ajutorul cookieurilor:<br /> &ndash; Particularizati-va setarile browserului in ceea ce priveste cookie-urile pentru a reflecta un nivel confortabil pentru voi al securitatii utilizarii cookie-urilor.<br /> &ndash; Daca nu va deranjeaza cookie-urile si sunteti singura persoana care utilizaeaza computerul, puteti seta termene lunigi de expirare pentru stocarea istoricului de navigare si al datelor personale de acces.<br /> &ndash; Daca impartiti accesul la calculator, puteti lua in considerare setarea browserului pentru a sterge datele individuale de navigare de fiecare data cand inchideti browserul. Aceasta este o variant de a accesa site-urile care plaseaza cookieuri si de a sterge orice informatie de vizitare la inchiderea sesiunii navigare.<br /> &ndash; Instalati-va si updatati-va constant aplicatii antispyware.</p>*/
/* <p style="text-align: justify;">Multe dintre aplicatiile de detectare si prevenire a spyware-ului includ detectarea atacurilor pe site-uri.<br /> Astfel, impiedica browserul de la a accesa website-uri care ar putea sa exploateze vulnerabilitatile browserului sau sa descarce software periculos. Asigurati-va ca aveti browserul mereu updatat. Multe dintre atacurile bazate pe cookies se realizeaza exploatand punctele slabe ale versiunilor vechi ale browserelor.</p>*/
/* <p style="text-align: justify;"><br /> Cookie-urile sunt pretutindeni si nu pot fi evitate daca doriti sa va bucurati de acces pe cele mai bune si cele mai mari site-uri de pe Internet &ndash; locale sau internationale. Cu o intelegere clara a modului lor de operare si a beneficiilor pe care le aduc, puteti lua masurile necesare de securitate astel incat sa puteti naviga cu incredere pe internet.</p>*/
/* <p style="text-align: justify;">Cum pot opri cookie-urile?</p>*/
/* <p style="text-align: justify;"><br /> Dezactivarea si refuzul de a primi cookie-uri pot face anumite site-uri impracticabile sau dificil de vizitat si folosit. De asemenea, refuzul de a accepta cookie-uri nu inseamna ca nu veti mai primi/vedea publicitate online.</p>*/
/* <p style="text-align: justify;"><br /> Este posibila setarea din browser pentru ca aceste cookie-uri sa nu mai fie acceptate sau poti seta browserul sa accepte cookie-uri de la un site anume. Dar, de exemplu, daca nu esti inregistat folosind cookie-urile, nu vei putea lasa comentarii.<br /> Toate browserele moderne ofera posibilitatea de a schimba setarile cookie-urilor. Aceste setari se gasesc de regula in &bdquo;optiuni&rdquo; sau in meniul de &bdquo;preferinte&rdquo; al browserului tau.</p>*/
/* <p style="text-align: justify;"><br /> Pentru a intelege aceste setari, urmatoarele linkuri pot fi folositoare, altfel puteti folosi optiunea &bdquo;ajutor&rdquo; a browserului pentru mai multe detalii.</p>*/
/* <p style="text-align: justify;"><br /> Pentru setarile cookie-urilor generate de terti, puteti consulta si site-ul www.youronlinechoices.com/ro/ unde gasiti mai multe informatii privind confidentialitatea legata de publicitatea online. </p>*/
/*             </div>*/
/* */
/*     </section><!--/#feature-->*/
